//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LB_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.BooksInfo = new HashSet<BooksInfo>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int IdAuthor { get; set; }
        public int IdGenre { get; set; }
        public int IdPublisher { get; set; }
        public int IdSeries { get; set; }
        public int Pages { get; set; }
        public int Year { get; set; }
        public decimal Sale_price { get; set; }
        public decimal Coste_price { get; set; }
        public int Amount { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Genres Genres { get; set; }
        public virtual Publishers Publishers { get; set; }
        public virtual Series Series { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BooksInfo> BooksInfo { get; set; }
    }
}
