//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LB_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksInfo
    {
        public int Id { get; set; }
        public int IdBook { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
    
        public virtual Books Books { get; set; }
    }
}
